### ISSUE TITLE
Small enhancement

### ISSUE THREAD

**Issue by musooff** [MARGI3/StretchTopNestedScrollView#1]
https://github.com/MARGI3/OverScrollNestedScrollView/blob/5005fe3d43a0baa506c424d0b552740e0b800198/app/src/main/java/com/overscroll/demo/OverScrollBounceBehavior.java#L88

above line should be
```
mTargetView.getLayoutParams().height = mNormalHeight + Math.abs(mOverScrollY); 
```

**Comment by MARGI3** [comment]
👍 Thanks for your tips, i have update it
